export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Fascinating Stories',
    headline: 'Enter into The Intriguing Mind',
    description: 'Time travel is possible if and only if you have the right tools for it and that is what you get here.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/img1.jpg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Virtual Storybook',
    headline: 'Your favorite story is always with you',
    description: 'Enjoy stories directly from your device and read them anytime, anywhere without the burden of paperback.',
    buttonLabel: 'Read More',
    imgStart: true,
    img: require('../../images/img2.jpg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Join Our Team',
    headline: 'Have your work showcased',
    description: 'If you are a good writer, then join us to have your work on display for your benefit.',
    buttonLabel: 'Join Us',
    imgStart: false,
    img: require('../../images/img5.jpg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};